# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Configuration-Changelog
# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3.0-Configuration-Changelog
debug: false

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    basedir: /home/temp
  servlet:
    context-path: ''
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  #      force-response: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true
    path: /error

#logging:
#  level:
#    root: info
#    io.github: debug
#    #    org.springframework: warn
#    org.springframework: info

mybatis-plus:
  #  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: io.github.entity
  # 自定义类型转换处理器包名
  #  type-handlers-package: io.github.common.typehandler
  check-config-location: true
  configuration:
    cache-enabled: false
    log-prefix: bootplus.dao.
    map-underscore-to-camel-case: true
  global-config:
    banner: true
    db-config:
      id-type: auto
      table-underline: true

spring:
  application:
    name: ${application.name}
  aop:
    auto: true
    proxy-target-class: true
  profiles:
    active: dev
  # 生产环境
  #    active: prd
  jackson:
    default-property-inclusion: non_null
    # 取消timestamps形式
    serialization: { WRITE_DATES_AS_TIMESTAMPS: false, WRITE_ENUMS_USING_TO_STRING: true }
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    ehcache:
      config: classpath:/ehcache-core.xml
  #    type: EHCACHE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bootplus?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    druid:
      #      filters: stat,wall,slf4j
      filter:
        stat:
          enabled: true
        wall:
          config:
            # 批量操作
            multi-statement-allow: true
          enabled: true
        slf4j:
          enabled: true
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;password=${spring.datasource.password}
      validation-query: SELECT 1 FROM DUAL
      # 注册DruidFilter拦截(网络url监控统计)
      web-stat-filter:
        enabled: false
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      # 注册DruidServlet（监控页面）
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        # 是否能够重置数据
        reset-enable: false
        allow: 127.0.0.1
  freemarker:
    allow-request-override: false
    cache: false
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: rc
    settings:
      number_format: 0.##
      # freemarker.core.Configurable#setSetting
      # freemarker.template.Configuration#setSetting
      tag_syntax: auto_detect
    suffix: .ftl
    check-template-location: true
    template-loader-path:
      - classpath:/templates/
  messages:
    encoding: UTF-8
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/statics/
      - classpath:/public/
  data:
    jpa:
      repositories:
        enabled: false
    redis:
      repositories:
        enabled: false
  redis:
    # TODO 接入
    timeout: 3000
    password: test
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  # Spring Security Default user name and password
  security:
    user:
      name: admin
      password: admin
      roles: admin
  jpa:
    open-in-view: false
  quartz:
    # 覆盖已存在的任务
    overwrite-existing-jobs: true

management:
  endpoint:
    health:
      show-details: always
  server:
  #    port: 8090
  #    servlet:
  #      context-path: /monitor
  endpoints:
    web:
      # io.github.config.ActuatorWebSecurityConfig
      base-path: /admin/monitor

################################### 程序自定义配置 ###################################

application:
  name: @project.artifactId@
  version: @project.version@
  url: @project.url@
  description: @project.description@
  blog: @blog.url@
  basedir: @project.basedir@
  requestPassword: aAr9MVS9j1
  #  管理员ID
  admin-id: 1
  logs:
    level: DEBUG
    path: ${application.basedir}/../logs
  # 自定义线程池配置
  thread-pool:
    core-pool-size: 3
    max-pool-size: 2000
    queue-capacity: 200
    keep-alive-seconds: 3000
    thread-name-prefix: ${application.name:zhousiwei}-task-
  mvc:
    view-resolves:
      - {urlPath: '/',viewName: 'redirect:/admin'}
  file-config:
    # 文件上传保存路径
    upload-path: ${application.basedir}/../upload
  junit-env:
    admin-name: admin
    admin-pwd: admin
